tools:
  gemini:
    description: Strategic analysis, hypothesis validation, framework explanations
    command: gemini
    enabled: true
  codex:
    description: Code-level review, specific fix suggestions, bug identification
    command: codex
    enabled: false
  cursor-agent:
    description: Repository-wide discovery, finding patterns, impact analysis
    command: cursor-agent
    enabled: true
models:
  gemini:
    priority:
    - gemini-2.5-pro
    flags: []
  codex:
    priority:
    - cheetah
    flags:
    - --skip-git-repo-check
  cursor-agent:
    priority:
    - cheetah
    flags: []
  overrides: []
consensus:
  pairs:
    default:
    - cursor-agent
    - gemini
    code-focus:
    - cursor-agent
    - gemini
    discovery-focus:
    - cursor-agent
    - gemini
  auto_trigger:
    default: default
    fixture: code-focus
    flaky: default
    multi-file: discovery-focus
    timeout: default
    exception: code-focus
consultation:
  timeout_seconds: 90
